[package]
name = "eff"
version = "0.0.2-alpha.0"
authors = ["pan"]
edition = "2018"

description = "Algebraic Effects Library for Rust"
repository = "https://github.com/pandaman64/effective-rust/"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
eff-attr = { path = "./eff-attr" }
coproduct = { path = "./coproduct" }
proc-macro-hack = "0.5.4"
rich-phantoms = "0.1.0"
