[package]
name = "eff-attr"
version = "0.0.1"
authors = ["pandaman64 <kointosudesuyo@infoseek.jp>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
proc-macro-hack = "0.5.4"
syn = { version = "0.15.23", features = ["extra-traits", "full", "visit-mut"] }
quote = "0.6.10"
