[package]
name = "eff-attr"
version = "0.0.2"
authors = ["pandaman64 <kointosudesuyo@infoseek.jp>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
proc-macro-hack = "0.5"
syn = { version = "0.15", features = ["full"] }
quote = "0.6"
